headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[functions]

[functions."*"]

[build]
publish = "D:\\Flutter_projects\\galaxydox\\build\\web"
publishOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/well-known/assetlinks.json"

[headers.values]
Content-Type = "application/json; charset=utf-8"
X-Content-Type-Options = "nosniff"
Cache-Control = "no-store, no-cache, must-revalidate"

[[headers]]
for = "/well-known/apple-app-site-association"

[headers.values]
Content-Type = "application/json; charset=utf-8"
X-Content-Type-Options = "nosniff"
Cache-Control = "no-store, no-cache, must-revalidate"

[[headers]]
for = "/.well-known/assetlinks.json"

[headers.values]
Content-Type = "application/json; charset=utf-8"
X-Content-Type-Options = "nosniff"
Cache-Control = "no-store, no-cache, must-revalidate"

[[headers]]
for = "/.well-known/apple-app-site-association"

[headers.values]
Content-Type = "application/json; charset=utf-8"
X-Content-Type-Options = "nosniff"
Cache-Control = "no-store, no-cache, must-revalidate"

[[headers]]
for = "/apple-app-site-association"

[headers.values]
Content-Type = "application/json; charset=utf-8"
X-Content-Type-Options = "nosniff"
Cache-Control = "no-store, no-cache, must-revalidate"

[[headers]]
for = "/well-known/assetlinks.json"

[headers.values]
Content-Type = "application/json; charset=utf-8"
X-Content-Type-Options = "nosniff"
Access-Control-Allow-Origin = "*"

[[headers]]
for = "/well-known/apple-app-site-association"

[headers.values]
Content-Type = "application/json; charset=utf-8"
X-Content-Type-Options = "nosniff"

[[headers]]
for = "/apple-app-site-association"

[headers.values]
Content-Type = "application/json; charset=utf-8"
X-Content-Type-Options = "nosniff"

[[redirects]]
from = "/.well-known/*"
to = "/well-known/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/admin"
to = "/admin/login"
status = 302.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/admin/*"
to = "https://galaxydoxadmin.netlify.app/admin/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]