// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAk1oNwhaziHIMPYYr5OdQm07CYBh9zXQ',
    appId: '1:713971911557:web:6c2c249ee55acbbd5692ec',
    messagingSenderId: '713971911557',
    projectId: 'galaxydox-d25e9',
    authDomain: 'galaxydox-d25e9.firebaseapp.com',
    storageBucket: 'galaxydox-d25e9.firebasestorage.app',
    measurementId: 'G-Y7DBWWDLMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpZ2pZvP5MT3TNHewq4ilMiZz7GOa2QqA',
    appId: '1:713971911557:android:d7d439b620e77b075692ec',
    messagingSenderId: '713971911557',
    projectId: 'galaxydox-d25e9',
    storageBucket: 'galaxydox-d25e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbUpxu-3GYdiCjmJYJE2LXsyYMuiUCcOs',
    appId: '1:713971911557:ios:037be02b89d2a9015692ec',
    messagingSenderId: '713971911557',
    projectId: 'galaxydox-d25e9',
    storageBucket: 'galaxydox-d25e9.firebasestorage.app',
    iosBundleId: 'com.galaxydox.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAk1oNwhaziHIMPYYr5OdQm07CYBh9zXQ',
    appId: '1:713971911557:web:52b1d323cec9298b5692ec',
    messagingSenderId: '713971911557',
    projectId: 'galaxydox-d25e9',
    authDomain: 'galaxydox-d25e9.firebaseapp.com',
    storageBucket: 'galaxydox-d25e9.firebasestorage.app',
    measurementId: 'G-L0YPVG9HQM',
  );
}
